# Generated by Django 4.0.2 on 2022-02-11 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hostname')),
                ('last_crawl', models.DateTimeField(verbose_name='Last crawl time')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048, verbose_name='URL')),
                ('mime', models.CharField(max_length=255, verbose_name='Mime type')),
                ('last_crawl', models.DateTimeField(verbose_name='Last crawl time')),
                ('etag', models.CharField(max_length=1024, verbose_name='ETag')),
                ('title', models.CharField(max_length=2048, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='searchdb.host', verbose_name='Hostname')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
    ]
