# Generated by Django 4.0.2 on 2022-02-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='url',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='url',
            name='etag',
            field=models.CharField(blank=True, max_length=1024, verbose_name='ETag'),
        ),
        migrations.AlterField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=2048, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=2048, unique=True, verbose_name='URL'),
        ),
    ]
