# Generated by Django 4.0.2 on 2022-02-11 03:32

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb', '0002_alter_host_name_alter_url_content_alter_url_etag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='etag',
        ),
        migrations.RemoveField(
            model_name='url',
            name='mime',
        ),
        migrations.AddField(
            model_name='url',
            name='headers',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True, verbose_name='Response headers'),
        ),
    ]
