# Generated by Django 4.0.2 on 2022-02-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb', '0003_remove_url_etag_remove_url_mime_url_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Title'),
        ),
    ]
