# Generated by Django 4.0.2 on 2022-02-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb', '0004_alter_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='excerpt',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='url',
            name='content',
            field=models.BinaryField(blank=True, verbose_name='Content'),
        ),
    ]
