# Generated by Django 4.0.2 on 2022-02-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb', '0005_url_excerpt_alter_url_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Extracted text'),
        ),
    ]
